[package]
name = "PriceOracle"
type = "contract"
authors = ["Onyx Team"]
compiler_version = ">=0.1.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v2.1.8", directory = "noir-projects/aztec-nr/aztec" }
